site_name: SRS Template
plugins:
    - search
    #- pdf-export:
        #combined: true

markdown_extensions:
    - admonition
    - codehilite:
        linenums: true

theme: 
    name: 'material'
    palette:
        primary: Blue
    feature:
        tabs: false

nav:
    - 'index.md'
    - '1-summary-background.md'
    - '2-goals.md'
    - '3-requirements.md'
    - '4-nonfunctional-requirements.md'
    - '5-plan.md'
    - '6-security-privacy-risks.md'
    - '7-other-considerations.md'
    - '8-milestones.md'
    - '9-open-questions.md'
